#include "srchilite_map.hh"

#include <algorithm>
#include <map>


namespace widget {

  namespace {

    const std::map<std::string, source_highlight_data> srchilite_map{
      {"ac", {"m4.lang", "m4"}},
      {"ada", {"ada.lang", "Ada"}},
      {"adb", {"ada.lang", "Ada"}},
      {"am", {"makefile.lang", "Makefile"}},
      {"applescript", {"applescript.lang", "Applescript"}},
      {"asm", {"asm.lang", "Asm"}},
      {"autoconf", {"m4.lang", "m4"}},
      {"awk", {"awk.lang", "AWK"}},
      {"bash", {"sh.lang", "Bash"}},
      {"bat", {"bat.lang", "Bat"}},
      {"batch", {"bat.lang", "Bat"}},
      {"bib", {"bib.lang", "BibTeX"}},
      {"bison", {"bison.lang", "Bison"}},
      {"c", {"c.lang", "C"}},
      {"caml", {"caml.lang", "Caml"}},
      {"cbl", {"cobol.lang", "Cobol"}},
      {"cc", {"cpp.lang", "C++"}},
      {"changelog", {"changelog.lang", "ChangeLog"}},
      {"clipper", {"clipper.lang", "Clipper"}},
      {"cls", {"latex.lang", "LaTeX"}},
      {"cobol", {"cobol.lang", "Cobol"}},
      {"coffee", {"coffeescript.lang", "Coffeescript"}},
      {"coffeescript", {"coffeescript.lang", "Coffeescript"}},
      {"conf", {"conf.lang", "Conf"}},
      {"cpp", {"cpp.lang", "C++"}},
      {"cs", {"csharp.lang", "C#"}},
      {"csh", {"sh.lang", "Csh"}},
      {"csharp", {"csharp.lang", "C#"}},
      {"css", {"css.lang", "CSS"}},
      {"ctp", {"php.lang", "PHP"}},
      {"cxx", {"cpp.lang", "C++"}},
      {"d", {"d.lang", "D"}},
      {"desktop", {"desktop.lang", "Desktop"}},
      {"diff", {"diff.lang", "Diff"}},
      {"dmd", {"d.lang", "D"}},
      {"docbook", {"xml.lang", "DocBook"}},
      {"dtx", {"latex.lang", "LaTeX"}},
      {"el", {"lisp.lang", "Emacs Lisp"}},
      {"eps", {"postscript.lang", "Postscript"}},
      {"erl", {"erlang.lang", "Erlang"}},
      {"erlang", {"erlang.lang", "Erlang"}},
      {"errors", {"errors.lang", "Errors"}},
      {"f", {"fortran.lang", "Fortran"}},
      {"f77", {"fortran.lang", "Fortran"}},
      {"f90", {"fortran.lang", "Fortran"}},
      {"feature", {"feature.lang", "Features"}},
      {"fixed-fortran", {"fixed-fortran.lang", "Fixed Fortran"}},
      {"flex", {"flex.lang", "Lex"}},
      {"fortran", {"fortran.lang", "Fortran"}},
      {"free-fortran", {"fortran.lang", "Fortran"}},
      {"glsl", {"glsl.lang", "GLSL"}},
      {"go", {"go.lang", "Go"}},
      {"groovy", {"groovy.lang", "Groovy"}},
      {"h", {"cpp.lang", "C++"}},
      {"haskell", {"haskell.lang", "Haskell"}},
      {"haxe", {"haxe.lang", "Haxe"}},
      {"hh", {"cpp.lang", "C++"}},
      {"hpp", {"cpp.lang", "C++"}},
      {"hs", {"haskell.lang", "Haskell"}},
      {"htm", {"html.lang", "HTML"}},
      {"html", {"html.lang", "HTML"}},
      {"hx", {"haxe.lang", "Haxe"}},
      {"hxx", {"cpp.lang", "C++"}},
      {"in", {"makefile.lang", "Makefile"}},
      {"ini", {"desktop.lang", "Desktop"}},
      {"ipxe", {"ipxe.lang", "IPXE"}},
      {"islisp", {"islisp.lang", "ISLisp"}},
      {"java", {"java.lang", "Java"}},
      {"javalog", {"javalog.lang", "Javalog"}},
      {"javascript", {"javascript.lang", "Javascript"}},
      {"js", {"javascript.lang", "Javascript"}},
      {"json", {"json.lang", "JSON"}},
      {"kcfg", {"xml.lang", "XML"}},
      {"kdevelop", {"xml.lang", "XML"}},
      {"kidl", {"xml.lang", "KIDL"}},
      {"ksh", {"sh.lang", "Ksh"}},
      {"l", {"flex.lang", "Lex"}},
      {"lang", {"langdef.lang", "Langdef"}},
      {"langdef", {"langdef.lang", "Langdef"}},
      {"latex", {"latex.lang", "LaTeX"}},
      {"ldap", {"ldap.lang", "LDAP"}},
      {"ldif", {"ldap.lang", "LDAP"}},
      {"lex", {"flex.lang", "Lex"}},
      {"lgt", {"logtalk.lang", "Logtalk"}},
      {"lhs", {"haskell_literate.lang", "Literate Haskell"}},
      {"lilypond", {"lilypond.lang", "Lilypond"}},
      {"lisp", {"lisp.lang", "LISP"}},
      {"ll", {"flex.lang", "Lex"}},
      {"log", {"log.lang", "Log"}},
      {"logtalk", {"logtalk.lang", "Logtalk"}},
      {"lsm", {"lsm.lang", "LSM"}},
      {"lua", {"lua.lang", "Lua"}},
      {"ly", {"lilypond.lang", "Lilypond"}},
      {"m4", {"m4.lang", "m4"}},
      {"makefile", {"makefile.lang", "Makefile"}},
      {"manifest", {"manifest.lang", "Manifest"}},
      {"mf", {"manifest.lang", "Manifest"}},
      {"ml", {"caml.lang", "Caml"}},
      {"mli", {"caml.lang", "Caml"}},
      {"moc", {"cpp.lang", "C++"}},
      {"opa", {"opa.lang", "OPA"}},
      {"outlang", {"outlang.lang", "Outlang"}},
      {"oz", {"oz.lang", "Oz"}},
      {"pas", {"pascal.lang", "Pascal"}},
      {"pascal", {"pascal.lang", "Pascal"}},
      {"patch", {"diff.lang", "Diff"}},
      {"pc", {"pc.lang", "PkgConfig"}},
      {"perl", {"perl.lang", "Perl"}},
      {"php", {"php.lang", "PHP"}},
      {"php3", {"php.lang", "PHP"}},
      {"php4", {"php.lang", "PHP"}},
      {"php5", {"php.lang", "PHP"}},
      {"pkgconfig", {"pc.lang", "PkgConfig"}},
      {"pl", {"prolog.lang", "Prolog"}},
      {"pm", {"perl.lang", "Perl"}},
      {"po", {"po.lang", "PO File"}},
      {"postscript", {"postscript.lang", "Postscript"}},
      {"pot", {"po.lang", "PO File"}},
      {"prg", {"clipper.lang", "Clipper"}},
      {"prolog", {"prolog.lang", "Prolog"}},
      {"properties", {"properties.lang", "Properties"}},
      {"proto", {"proto.lang", "Protobuf"}},
      {"protobuf", {"proto.lang", "Protobuf"}},
      {"ps", {"postscript.lang", "Postscript"}},
      {"py", {"python.lang", "Python"}},
      {"python", {"python.lang", "Python"}},
      {"r", {"r.lang", "R"}},
      {"rb", {"ruby.lang", "Ruby"}},
      {"rc", {"xml.lang", "XML"}},
      {"rpm-spec", {"spec.lang", "RPM"}},
      {"rs", {"rust.lang", "Rust"}},
      {"ruby", {"ruby.lang", "Ruby"}},
      {"s", {"s.lang", "S"}},
      {"scala", {"scala.lang", "Scala"}},
      {"scheme", {"scheme.lang", "Scheme"}},
      {"scm", {"scheme.lang", "Scheme"}},
      {"scpt", {"applescript.lang", "Applescript"}},
      {"sh", {"sh.lang", "Sh"}},
      {"shell", {"sh.lang", "Sh"}},
      {"sig", {"sml.lang", "SML"}},
      {"sl", {"slang.lang", "Slang"}},
      {"slang", {"slang.lang", "Slang"}},
      {"slsh", {"slang.lang", "Slang"}},
      {"sml", {"sml.lang", "SML"}},
      {"spec", {"spec.lang", "Spec"}},
      {"sql", {"sql.lang", "SQL"}},
      {"sty", {"latex.lang", "LaTeX"}},
      {"style", {"style.lang", "Style"}},
      {"syslog", {"log.lang", "Log"}},
      {"tcl", {"tcl.lang", "Tcl"}},
      {"tcsh", {"sh.lang", "Tcsh"}},
      {"tex", {"latex.lang", "TeX"}},
      {"texi", {"texinfo.lang", "Texinfo"}},
      {"texinfo", {"texinfo.lang", "Texinfo"}},
      {"tk", {"tcl.lang", "Tk"}},
      {"tml", {"tml.lang", "TML"}},
      // {"txt", {"nohilite.lang", ""}},
      {"ui", {"xml.lang", "XML"}},
      {"upc", {"upc.lang", "UPC"}},
      {"vala", {"vala.lang", "Vala"}},
      {"vbs", {"vbscript.lang", "VBScript"}},
      {"vbscript", {"vbscript.lang", "VBScript"}},
      {"vim", {"vim.lang", "Vim"}},
      {"xhtml", {"xml.lang", "XML"}},
      {"xml", {"xml.lang", "XML"}},
      {"xorg", {"xorg.lang", "Xorg"}},
      {"y", {"bison.lang", "Yacc"}},
      {"yacc", {"bison.lang", "Yacc"}},
      {"yy", {"bison.lang", "Yacc"}},
      {"zsh", {"zsh.lang", "Zsh"}},
    };

  }

  std::optional<source_highlight_data> find_source_highlight_data(const std::string& s)
  {
    auto it = srchilite_map.find(s);
    if (it == srchilite_map.end()) {
      std::string slower;
      // All the names are ASCII-only, no need to consider UTF-8 encoding.
      std::ranges::transform(s, std::back_inserter(slower), [](auto ch) { return tolower(ch); });
      it = srchilite_map.find(slower);
    }

    if (it != srchilite_map.end())
      return it->second;

    return {};
  }

} // namespace widget
